import { Surah, ReciterMap } from './types';

// Manual mapping of MP3Quran names to EveryAyah identifiers
// Only including verified, reliable sources to ensure range download works correctly.
// Removed reciters with incomplete or missing EveryAyah files (e.g., Khalid Al Jaleel).
export const EVERY_AYAH_MAPPING: ReciterMap = {
  'مشاري العفاسي': 'Alafasy_128kbps',
  'ماهر المعيقلي': 'MaherAlMuaiqly128kbps',
  'عبدالرحمن السديس': 'Abdurrahmaan_As-Sudais_192kbps',
  'سعود الشريم': 'Saood_ash-Shuraym_128kbps',
  'سعد الغامدي': 'Saad_Al-Ghamdi_128kbps',
  'ياسر الدوسري': 'Yasser_Ad-Dussary_128kbps',
  'أحمد العجمي': 'Ahmed_ibn_Ali_al-Ajamy_128kbps',
  'فارس عباد': 'Fares_Abbad_128kbps',
  'ناصر القطامي': 'Nasser_Alqatami_128kbps',
  'محمود خليل الحصري': 'Husary_128kbps',
  'محمد صديق المنشاوي': 'Minshawy_Murattal_128kbps',
  'عبدالباسط عبدالصمد': 'Abdul_Basit_Murattal_192kbps',
  'محمود علي البنا': 'Mahmoud_Ali_al-Banna_32kbps',
  'عبدالله بصفر': 'Abdullah_Basfar_192kbps',
  'أبوبكر الشاطري': 'Abu_Bakr_Ash-Shatri_128kbps',
  'هاني الرفاعي': 'Hani_Rifai_192kbps',
  'علي الحذيفي': 'Ali_Al-Hudhaify_128kbps',
  'خليفة الطنيجي': 'Khalifa_Al_Tunaiji_64kbps',
  'محمد جبريل': 'Muhammad_Jibreel_128kbps',
  'محمد الطبلاوي': 'Mohammad_al_Tablaway_128kbps',
  'عبدالله عواد الجهني': 'Abdullaah_3awwaad_Al-Juhaynee_128kbps',
  'محمد أيوب': 'Muhammad_Ayyoub_128kbps',
  'عبدالعزيز الأحمد': 'Abdel_Aziz_Al_Ahmed_128kbps'
};

export const SURAH_LIST: Surah[] = [
    { id: 1, name: "الفاتحة", englishName: "Al-Fatiha", ayahCount: 7, type: "Meccan" },
    { id: 2, name: "البقرة", englishName: "Al-Baqarah", ayahCount: 286, type: "Medinan" },
    { id: 3, name: "آل عمران", englishName: "Al-Imran", ayahCount: 200, type: "Medinan" },
    { id: 4, name: "النساء", englishName: "An-Nisa", ayahCount: 176, type: "Medinan" },
    { id: 5, name: "المائدة", englishName: "Al-Ma'idah", ayahCount: 120, type: "Medinan" },
    { id: 6, name: "الأنعام", englishName: "Al-An'am", ayahCount: 165, type: "Meccan" },
    { id: 7, name: "الأعراف", englishName: "Al-A'raf", ayahCount: 206, type: "Meccan" },
    { id: 8, name: "الأنفال", englishName: "Al-Anfal", ayahCount: 75, type: "Medinan" },
    { id: 9, name: "التوبة", englishName: "At-Tawbah", ayahCount: 129, type: "Medinan" },
    { id: 10, name: "يونس", englishName: "Yunus", ayahCount: 109, type: "Meccan" },
    { id: 11, name: "هود", englishName: "Hud", ayahCount: 123, type: "Meccan" },
    { id: 12, name: "يوسف", englishName: "Yusuf", ayahCount: 111, type: "Meccan" },
    { id: 13, name: "الرعد", englishName: "Ar-Ra'd", ayahCount: 43, type: "Medinan" },
    { id: 14, name: "إبراهيم", englishName: "Ibrahim", ayahCount: 52, type: "Meccan" },
    { id: 15, name: "الحجر", englishName: "Al-Hijr", ayahCount: 99, type: "Meccan" },
    { id: 16, name: "النحل", englishName: "An-Nahl", ayahCount: 128, type: "Meccan" },
    { id: 17, name: "الإسراء", englishName: "Al-Isra", ayahCount: 111, type: "Meccan" },
    { id: 18, name: "الكهف", englishName: "Al-Kahf", ayahCount: 110, type: "Meccan" },
    { id: 19, name: "مريم", englishName: "Maryam", ayahCount: 98, type: "Meccan" },
    { id: 20, name: "طه", englishName: "Ta-Ha", ayahCount: 135, type: "Meccan" },
    { id: 21, name: "الأنبياء", englishName: "Al-Anbiya", ayahCount: 112, type: "Meccan" },
    { id: 22, name: "الحج", englishName: "Al-Hajj", ayahCount: 78, type: "Medinan" },
    { id: 23, name: "المؤمنون", englishName: "Al-Mu'minun", ayahCount: 118, type: "Meccan" },
    { id: 24, name: "النور", englishName: "An-Nur", ayahCount: 64, type: "Medinan" },
    { id: 25, name: "الفرقان", englishName: "Al-Furqan", ayahCount: 77, type: "Meccan" },
    { id: 26, name: "الشعراء", englishName: "Ash-Shu'ara", ayahCount: 227, type: "Meccan" },
    { id: 27, name: "النمل", englishName: "An-Naml", ayahCount: 93, type: "Meccan" },
    { id: 28, name: "القصص", englishName: "Al-Qasas", ayahCount: 88, type: "Meccan" },
    { id: 29, name: "العنكبوت", englishName: "Al-Ankabut", ayahCount: 69, type: "Meccan" },
    { id: 30, name: "الروم", englishName: "Ar-Rum", ayahCount: 60, type: "Meccan" },
    { id: 31, name: "لقمان", englishName: "Luqman", ayahCount: 34, type: "Meccan" },
    { id: 32, name: "السجدة", englishName: "As-Sajdah", ayahCount: 30, type: "Meccan" },
    { id: 33, name: "الأحزاب", englishName: "Al-Ahzab", ayahCount: 73, type: "Medinan" },
    { id: 34, name: "سبأ", englishName: "Saba", ayahCount: 54, type: "Meccan" },
    { id: 35, name: "فاطر", englishName: "Fatir", ayahCount: 45, type: "Meccan" },
    { id: 36, name: "يس", englishName: "Ya-Sin", ayahCount: 83, type: "Meccan" },
    { id: 37, name: "الصافات", englishName: "As-Saffat", ayahCount: 182, type: "Meccan" },
    { id: 38, name: "ص", englishName: "Sad", ayahCount: 88, type: "Meccan" },
    { id: 39, name: "الزمر", englishName: "Az-Zumar", ayahCount: 75, type: "Meccan" },
    { id: 40, name: "غافر", englishName: "Ghafir", ayahCount: 85, type: "Meccan" },
    { id: 41, name: "فصلت", englishName: "Fussilat", ayahCount: 54, type: "Meccan" },
    { id: 42, name: "الشورى", englishName: "Ash-Shura", ayahCount: 53, type: "Meccan" },
    { id: 43, name: "الزخرف", englishName: "Az-Zukhruf", ayahCount: 89, type: "Meccan" },
    { id: 44, name: "الدخان", englishName: "Ad-Dukhan", ayahCount: 59, type: "Meccan" },
    { id: 45, name: "الجاثية", englishName: "Al-Jathiyah", ayahCount: 37, type: "Meccan" },
    { id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", ayahCount: 35, type: "Meccan" },
    { id: 47, name: "محمد", englishName: "Muhammad", ayahCount: 38, type: "Medinan" },
    { id: 48, name: "الفتح", englishName: "Al-Fath", ayahCount: 29, type: "Medinan" },
    { id: 49, name: "الحجرات", englishName: "Al-Hujurat", ayahCount: 18, type: "Medinan" },
    { id: 50, name: "ق", englishName: "Qaf", ayahCount: 45, type: "Meccan" },
    { id: 51, name: "الذاريات", englishName: "Ad-Dhariyat", ayahCount: 60, type: "Meccan" },
    { id: 52, name: "الطور", englishName: "At-Tur", ayahCount: 49, type: "Meccan" },
    { id: 53, name: "النجم", englishName: "An-Najm", ayahCount: 62, type: "Meccan" },
    { id: 54, name: "القمر", englishName: "Al-Qamar", ayahCount: 55, type: "Meccan" },
    { id: 55, name: "الرحمن", englishName: "Ar-Rahman", ayahCount: 78, type: "Medinan" },
    { id: 56, name: "الواقعة", englishName: "Al-Waqi'ah", ayahCount: 96, type: "Meccan" },
    { id: 57, name: "الحديد", englishName: "Al-Hadid", ayahCount: 29, type: "Medinan" },
    { id: 58, name: "المجادلة", englishName: "Al-Mujadila", ayahCount: 22, type: "Medinan" },
    { id: 59, name: "الحشر", englishName: "Al-Hashr", ayahCount: 24, type: "Medinan" },
    { id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", ayahCount: 13, type: "Medinan" },
    { id: 61, name: "الصف", englishName: "As-Saff", ayahCount: 14, type: "Medinan" },
    { id: 62, name: "الجمعة", englishName: "Al-Jumu'ah", ayahCount: 11, type: "Medinan" },
    { id: 63, name: "المنافقون", englishName: "Al-Munafiqun", ayahCount: 11, type: "Medinan" },
    { id: 64, name: "التغابن", englishName: "At-Taghabun", ayahCount: 18, type: "Medinan" },
    { id: 65, name: "الطلاق", englishName: "At-Talaq", ayahCount: 12, type: "Medinan" },
    { id: 66, name: "التحريم", englishName: "At-Tahrim", ayahCount: 12, type: "Medinan" },
    { id: 67, name: "الملك", englishName: "Al-Mulk", ayahCount: 30, type: "Meccan" },
    { id: 68, name: "القلم", englishName: "Al-Qalam", ayahCount: 52, type: "Meccan" },
    { id: 69, name: "الحاقة", englishName: "Al-Haqqah", ayahCount: 52, type: "Meccan" },
    { id: 70, name: "المعارج", englishName: "Al-Ma'arij", ayahCount: 44, type: "Meccan" },
    { id: 71, name: "نوح", englishName: "Nuh", ayahCount: 28, type: "Meccan" },
    { id: 72, name: "الجن", englishName: "Al-Jinn", ayahCount: 28, type: "Meccan" },
    { id: 73, name: "المزمل", englishName: "Al-Muzzammil", ayahCount: 20, type: "Meccan" },
    { id: 74, name: "المدثر", englishName: "Al-Muddaththir", ayahCount: 56, type: "Meccan" },
    { id: 75, name: "القيامة", englishName: "Al-Qiyamah", ayahCount: 40, type: "Meccan" },
    { id: 76, name: "الإنسان", englishName: "Al-Insan", ayahCount: 31, type: "Medinan" },
    { id: 77, name: "المرسلات", englishName: "Al-Mursalat", ayahCount: 50, type: "Meccan" },
    { id: 78, name: "النبأ", englishName: "An-Naba", ayahCount: 40, type: "Meccan" },
    { id: 79, name: "النازعات", englishName: "An-Nazi'at", ayahCount: 46, type: "Meccan" },
    { id: 80, name: "عبس", englishName: "Abasa", ayahCount: 42, type: "Meccan" },
    { id: 81, name: "التكوير", englishName: "At-Takwir", ayahCount: 29, type: "Meccan" },
    { id: 82, name: "الانفطار", englishName: "Al-Infitar", ayahCount: 19, type: "Meccan" },
    { id: 83, name: "المطففين", englishName: "Al-Mutaffifin", ayahCount: 36, type: "Meccan" },
    { id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", ayahCount: 25, type: "Meccan" },
    { id: 85, name: "البروج", englishName: "Al-Buruj", ayahCount: 22, type: "Meccan" },
    { id: 86, name: "الطارق", englishName: "At-Tariq", ayahCount: 17, type: "Meccan" },
    { id: 87, name: "الأعلى", englishName: "Al-A'la", ayahCount: 19, type: "Meccan" },
    { id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", ayahCount: 26, type: "Meccan" },
    { id: 89, name: "الفجر", englishName: "Al-Fajr", ayahCount: 30, type: "Meccan" },
    { id: 90, name: "البلد", englishName: "Al-Balad", ayahCount: 20, type: "Meccan" },
    { id: 91, name: "الشمس", englishName: "Ash-Shams", ayahCount: 15, type: "Meccan" },
    { id: 92, name: "الليل", englishName: "Al-Lail", ayahCount: 21, type: "Meccan" },
    { id: 93, name: "الضحى", englishName: "Ad-Duha", ayahCount: 11, type: "Meccan" },
    { id: 94, name: "الشرح", englishName: "Ash-Sharh", ayahCount: 8, type: "Meccan" },
    { id: 95, name: "التين", englishName: "At-Tin", ayahCount: 8, type: "Meccan" },
    { id: 96, name: "العلق", englishName: "Al-Alaq", ayahCount: 19, type: "Meccan" },
    { id: 97, name: "القدر", englishName: "Al-Qadr", ayahCount: 5, type: "Meccan" },
    { id: 98, name: "البينة", englishName: "Al-Bayyinah", ayahCount: 8, type: "Medinan" },
    { id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", ayahCount: 8, type: "Medinan" },
    { id: 100, name: "العاديات", englishName: "Al-Adiyat", ayahCount: 11, type: "Meccan" },
    { id: 101, name: "القارعة", englishName: "Al-Qari'ah", ayahCount: 11, type: "Meccan" },
    { id: 102, name: "التكاثر", englishName: "At-Takathur", ayahCount: 8, type: "Meccan" },
    { id: 103, name: "العصر", englishName: "Al-Asr", ayahCount: 3, type: "Meccan" },
    { id: 104, name: "الهمزة", englishName: "Al-Humazah", ayahCount: 9, type: "Meccan" },
    { id: 105, name: "الفيل", englishName: "Al-Fil", ayahCount: 5, type: "Meccan" },
    { id: 106, name: "قريش", englishName: "Quraish", ayahCount: 4, type: "Meccan" },
    { id: 107, name: "الماعون", englishName: "Al-Ma'un", ayahCount: 7, type: "Meccan" },
    { id: 108, name: "الكوثر", englishName: "Al-Kawthar", ayahCount: 3, type: "Meccan" },
    { id: 109, name: "الكافرون", englishName: "Al-Kafirun", ayahCount: 6, type: "Meccan" },
    { id: 110, name: "النصر", englishName: "An-Nasr", ayahCount: 3, type: "Medinan" },
    { id: 111, name: "المسد", englishName: "Al-Masad", ayahCount: 5, type: "Meccan" },
    { id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", ayahCount: 4, type: "Meccan" },
    { id: 113, name: "الفلق", englishName: "Al-Falaq", ayahCount: 5, type: "Meccan" },
    { id: 114, name: "الناس", englishName: "An-Nas", ayahCount: 6, type: "Meccan" }
];